### ISSUE TITLE
Stats.txt file being wiped/overriden when using the MultiSim module when the # of jobs >4x the number of processes available.

### ISSUE THREAD

**Issue by BobbyRBruce** [gem5/gem5#1738]
**Describe the bug**

In instances where the number of jobs exceeds four times the number of available processes, the MultiSim module overwrites/wipes the stats.txt of some jobs.

**Affects version**

At the time of writing, this bug affects MultiSim and has done since its incorporation into the simulator.

**To Reproduce**

Attached is a zip archive containing two files that you can use to reproduce the tests I ran to investigate this issue. Simply extract the two files and place them in the root directory of the gem5 repository. Then execute the "run_tests.sh" script.

[multisim-empty-stat-repro-package.zip](https://github.com/user-attachments/files/17583397/multisim-empty-stat-repro-package.zip)

These tests generate a cross-product of simulations differing in the number of available processes and jobs for gem5 MultiSim runs: 1 to 10 processes, each with simulations for 1 to 10 jobs, and then , for each job,verifying the existence of the stat.txt file and that it contained data. In other words, the tests execute the following commands "pseudocode":

```txt
for p in 1..10:
    for j in 1..10:
    1) Run multsim with j jobs using p processes, up to the maximum limit.
    2) Verify that all stat.txt files exist and are not empty.
```

The output of these tests shows that there are always failures in cases where the number of jobs is greater than 4 times the number of processes and always pass otherwise.

To directly observe this error and "play around" with it, you can use the "multisim-issue-reproduce-stats-override.py" script. It can be executed directly with a gem5 binary. Just modify the number of processes and jobs directly in the configuration file, then  execute the script and inspect the output directories for each job and their corresponding stats.txt files.

**Host ISA**
ARM (Apple Silicon machine)

**Compiler used**
Clang 16.0.0.0

**Comment by Harshil2107** [comment]
I am trying to reproduce this issue but I get a different error. The issue is essentially the same that the stats.txt file is overwritten to be empty but the last process fails with the error. By last process I mean the last one to finish and not the last one run.

```
Exception ignored in: <function Pool.__del__ at 0x77459fd7d9e0>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 271, in __del__
    self._change_notifier.put(None)
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 427, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
```

This happens in all cases when:
- number of processes > number of jobs
- number of processes = number of jobs
- number of processes < number of jobs

This error happens till number of jobs is 4 time the number of processes. The error changes when number of jobs > 4x number of processes.
